project_id = "vxiipdlmkhcmkliygoyg"

[functions.send-task-notification]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.check-delayed-tasks]
verify_jwt = false

[functions.reset-monthly-targets]
verify_jwt = false

[functions.calculate-sla-deadline]
verify_jwt = false

[functions.check-late-acknowledgements]
verify_jwt = false
